{"time":"2025-05-30T21:38:10.7345732+08:00","level":"INFO","msg":"stream: starting","core version":"0.19.11","symlink path":"D:\\Courses\\NLP\\NLP2025\\wandb\\run-20250530_213810-b707y2qe\\logs\\debug-core.log"}
{"time":"2025-05-30T21:38:33.5987304+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T21:38:56.9178245+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-30T21:39:22.4905416+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
